added another test and improved test suite output

diff --git a/tests/Makefile b/tests/Makefile
--- a/tests/Makefile
+++ b/tests/Makefile
@@ -10,12 +10,17 @@ default:
 	@echo "Run  make test  to run the test suite."
 
 test:
-	@for d in *test/ ; do \
-		echo "Running test $$d" ; \
+	@set -e ; for d in *-test ; do \
+		echo "" ; \
+		echo "\033[01mRunning test $$d...\033[0m" ; \
 		cd $$d ; \
 		mkdir -p $(OUTPUTDIR) ; \
-		$(MAKE) -B test PDFLATEX=$(PDFLATEX) ; \
-		done
+		$(MAKE) -B test PDFLATEX=$(PDFLATEX) || (echo "\033[01;31mFailed!\033[0m" ; exit 1) ; \
+		cd .. ; \
+		echo "\033[01;32mSuccess!\033[0m" ; \
+	done
+	@echo ""
+	@echo "\033[01;32mAll tests successful!\033[0m" ; \
 
 clean:
 	rm -rf ./*/$(OUTPUTDIR)
